fix(vispy): handle case where no rotation is required
Otherwise scipy errors with:

```
  File ".../pyneuroml/plot/PlotMorphologyVispy.py", line 1714, in create_mesh
    rot_obj = Rotation.from_matrix(rot_matrix)
  File "_rotation.pyx", line 1136, in scipy.spatial.transform._rotation.Rotation.from_matrix
ValueError: Non-positive determinant (left-handed or null coordinate frame) in rotation matrix 0: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]].

```